CREATE TABLE problem_report (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  update_timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  create_timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  response_id INT(10) UNSIGNED NOT NULL,
  show_hidden TINYINT(1) NOT NULL,
  page_name VARCHAR(255) NOT NULL,
  remote_address VARCHAR(45) NULL DEFAULT NULL,
  user_agent VARCHAR(255) NULL DEFAULT NULL,
  brand VARCHAR(127) NULL DEFAULT NULL,
  platform VARCHAR(127) NULL DEFAULT NULL,
  mobile VARCHAR(127) NULL DEFAULT NULL,
  datetime DATETIME NOT NULL,
  description TEXT NOT NULL,
  PRIMARY KEY (id),
  INDEX fk_response_id (response_id ASC),
  CONSTRAINT fk_problem_report_response_id
    FOREIGN KEY (response_id)
    REFERENCES pine.response (id)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_general_ci;
